### ISSUE TITLE
Пожалуйста уберите лишние красивости из UTF-8

### ISSUE THREAD

**Issue by ache** [ValdikSS/blockcheck#10]
Я понимаю, модно, но не у всех Linux, и экзотические UTF-8 символы в KOI8-R питон перекодировать не может, как ни старается:
  File "blockcheck.py", line 115, in test_dns
    print("[\u2713] DNS записи не подменяются")
  File "blockcheck.py", line 48, in print
    **builtins**.print(_args, *_kwargs)
  File "/usr/local/lib/python3.3/encodings/koi8_r.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 1: character maps to <undefined>

**Comment by ValdikSS** [comment]
Исправлено.
