### ISSUE TITLE
Ошибка определения открытия сайта

### ISSUE THREAD

**Issue by zikasak** [ValdikSS/blockcheck#21]
Здравствуйте. 
Программа определяет, что у меня открывается, например, http://www.lostfilm.tv. Однако при переходе по этому адресу вручную выскакивает заглушка провайдера о блокировке.

Оператор: Онлайм (Ростелеком)

**Comment by ValdikSS** [comment]
Пожалуйста, приложите полный лог программы. Предполагаю, что ваш провайдер использует подмену или перенаправление DNS, а программа обращается напрямую к IP сайта, игнорируя провайдерский DNS. Это ожидаемое поведение.

**Comment by zikasak** [comment]
Сейчас внимательней посмотрел на вывод программы. Перепутал строчки. все показывает правильно.
