### ISSUE TITLE
С sukebei.nyaa.se по-прежнему проблемы (уже по новому IP)

### ISSUE THREAD

**Issue by d-Metrius** [ValdikSS/blockcheck#22]
```
user@microserver:~/blockcheck$ ./blockcheck.py 
[O] Тестируем DNS
[O] Получаем эталонные DNS с сервера
	Эталонные адреса:		 ['104.28.16.79', '104.28.17.79', '5.178.68.100', '69.165.95.242', '78.110.160.185']
	Адреса через системный DNS:	 ['104.28.16.79', '104.28.17.79', '5.178.68.100', '69.165.95.242', '78.110.160.185']
	Адреса через Google DNS:	 ['104.28.16.79', '104.28.17.79', '5.178.68.100', '69.165.95.242', '78.110.160.185']
	Адреса через DNS AntiZapret:	 ['107.150.11.192', '107.150.11.192', '107.150.11.192', '107.150.11.192']
[✓] DNS записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем  http://sukebei.nyaa.se/
Traceback (most recent call last):
  File "./blockcheck.py", line 332, in <module>
    main()
  File "./blockcheck.py", line 275, in main
    http = test_http_access(False)
  File "./blockcheck.py", line 210, in test_http_access
    result = _get_url(site, ip=sites[site].get('ip') if by_ip else None)
  File "./blockcheck.py", line 132, in _get_url
    opened = urllib.request.urlopen(req, timeout=15, cadefault=True)
TypeError: urlopen() got an unexpected keyword argument 'cadefault'
```

**Comment by ValdikSS** [comment]
Установите Python 3.3 и новее.

**Comment by eisaev** [comment]
Ну или поправьте вот так:
--- blockcheck.orig.py	2016-02-16 19:52:55.445519323 +0500
+++ blockcheck.mod.py	2016-02-16 19:52:13.556298042 +0500
@@ -154,7 +154,7 @@
     req.add_header('User-Agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0')
 
     try:
-        opened = urllib.request.urlopen(req, timeout=15, cadefault=True)
+        opened = urllib.request.urlopen(req, timeout=15)
         output = opened.read()
     except (urllib.error.URLError, socket.error, socket.timeout) as e:
         if 'CERTIFICATE_VERIFY_FAILED' in str(e):
т.к. аргумент "cadefault" до python3.3 отсутствует, а после 3.3 игнорируется. Да и в 3.3: "This will only work on some non-Windows platforms."

**Comment by ValdikSS** [comment]
@eisaev так должно быть лучше.
