### ISSUE TITLE
Ошибочный результат проверки

### ISSUE THREAD

**Issue by Lucidyan** [ValdikSS/blockcheck#26]
[!] Результат:
[⚠] У вашего провайдера "полный" DPI. Он отслеживает ссылки даже внутри прокси, поэтому вам следует использовать любое шифрованное соединение, например, VPN или Tor.

Читаем выше:
[O] Тестируем HTTP
	Открываем  http://sukebei.nyaa.se/
[✓] Сайт открывается
	Открываем  http://www.lostfilm.tv/details.php?id=4141
[☠] Сайт не открывается
	Открываем  http://www.lostfilm.tv/
[✓] Сайт открывается
	Открываем  http://sukebei.nyaa.se/?page=view&tid=395631
[☠] Сайт не открывается
	Открываем  http://gelbooru.com/index.php?page=post&s=view&id=1989610
[☠] Сайт не открывается
	Открываем  http://gelbooru.com/
[✓] Сайт открывается
	Открываем через прокси  http://sukebei.nyaa.se/
[✓] Сайт открывается
	Открываем через прокси  http://www.lostfilm.tv/details.php?id=4141
[☠] Сайт не открывается
	Открываем через прокси  http://www.lostfilm.tv/
[☠] Сайт не открывается
	Открываем через прокси  http://sukebei.nyaa.se/?page=view&tid=395631
[✓] Сайт открывается
	Открываем через прокси  http://gelbooru.com/index.php?page=post&s=view&id=1989610
[✓] Сайт открывается
	Открываем через прокси  http://gelbooru.com/
[✓] Сайт открывается

http://www.lostfilm.tv/ открывается всегда
его подфорум - тоже, но содержимое видно только через иностранный прокси. 
Пчелайн

**Comment by ValdikSS** [comment]
Действительно. Спасибо за оповещение, я совсем забыл, что lostfilm из реестра убрали. Сейчас подумаю, на что бы его такое заменить.

**Comment by Lucidyan** [comment]
Спасибо за оперативность! Например, grani.ru с bitcoin.org неплохо порезали в свое время
А не могли бы вы помочь со смежным вопросом по dpi? https://toster.ru/q/214105
