### ISSUE TITLE
iam@valdikss.org.ru email seems to be invalid

### ISSUE THREAD

**Issue by leakeung** [ValdikSS/blockcheck#28]
Hello, I'm a Chinese. I asked your question before, iam@valdikss.org.ru mail seems to be invalid, hope to be able to recover, I have some question want to ask you.

**Comment by ValdikSS** [comment]
Hello.
It should work fine. I did't have any problems past week.

**Comment by leakeung** [comment]
Ok. Then I send a test email to you now.

**Comment by leakeung** [comment]
I just use Gmail sent an email to you. Has been shown to send. I don't know why

**Comment by ValdikSS** [comment]
I don't know either. It's a gmail account and right now I have email conversations without a problem.

**Comment by leakeung** [comment]
OK. If you are sure your mail no problem, it's probably an Gmail by GFW interference. I check is what reason.

**Comment by ValdikSS** [comment]
You can contact me over jabber: iam@valdikss.org.ru
