### ISSUE TITLE
How to build and install it from source code?

### ISSUE THREAD

**Issue by LavirtheWhiolet** [ValdikSS/blockcheck#29]

**Comment by ValdikSS** [comment]
You don't build it. Just run blockcheck.py and that's it. Build.py file in repository is for creating .exe flie for Windows.

**Comment by LavirtheWhiolet** [comment]
```
Traceback (most recent call last):
  File "blockcheck.py", line 9, in <module>
    import dns.resolver
ImportError: No module named 'dns'
```

**Comment by ValdikSS** [comment]
Install dnspython3 module either from the repository of your distro or using pip:

`pip install dnspython3`

**Comment by LavirtheWhiolet** [comment]
That helped, thanks. But the instructions should be added to "README.md" anyway.

<s>But what am I talking about? Just close it.</s>

**Comment by ValdikSS** [comment]
Fixed, thanks!
commit 71f96d41c049c483d89e6e7b038a0cf106dd4332

**Comment by antony3d** [comment]
У меня не сработало, как всё таки запустить.
└──▶ pip install dnspython3
Requirement already satisfied (use --upgrade to upgrade): dnspython3 in /usr/local/lib/python2.7/dist-packages
Cleaning up...
┌─(a3d)  (~/Downloads/blockcheck-master) 
└──▶ ./blockcheck.py 
Traceback (most recent call last):
  File "./blockcheck.py", line 9, in <module>
    import dns.resolver
ImportError: No module named dns.resolver

Я так подозреваю, что pip поставил библиотеку не туда ?

**Comment by ValdikSS** [comment]
У вас, похоже, по умолчанию в системе python 2, и pip, соответственно, тоже. Попробуйте pip3 или всегда работающий вариант python3 -m pip

**Comment by antony3d** [comment]
Да убунта 12.04, питон второй, но третий стоит и работает вполне.

└──▶ python3
python3               python3.2-dbg         python3.2dmu-config   python3-config        python3dmu            python3mu-config      
python3.2             python3.2-dbg-config  python3.2mu           python3-dbg           python3dmu-config     
python3.2-config      python3.2dmu          python3.2mu-config    python3-dbg-config    python3mu

Попробуйте pip3 или всегда работающий вариант python3 -m pip
└──▶ sudo apt-get install pip3
...
E: Unable to locate package pip3
└──▶ python3 -m pip
/usr/bin/python3: No module named pip

**Comment by ValdikSS** [comment]
`apt-get install python3-pip`
Не уверен, что у вас заработает с Python 3.2. Почему вы используете такой старый дистрибутив?

**Comment by antony3d** [comment]
E: Unable to locate package python3-pip
Эх.... Что ничего не получается. ;(
Старый такой дистр, потому что в нём очень много всего настроенно и установленно за эти года, и пеезжать на современный просто слишком долго и сложно.

Если нет больше идей, тогда наверное проще в виртуалке на 14.04 поробовать ?

**Comment by ValdikSS** [comment]
Как вариант, можете еще сделать virtualenv с python 3 и pip.

**Comment by antony3d** [comment]
Победил. Рассказываю. В ubunu 14.04 такая же ситуаци я питоном 2 и пип как я описал выше.
Все решается как вы и правильно сказали установкой pip3 вот только находится он в пакете python3-pip. Неплохо было бы если в рид.ми было указано, что для пользователей с питоном2 по умолчанию нужно ставить python3-pip и использовать команду pip3 install.

Спасибо за приложение, определило что провайдер вмешивается в https.
