### ISSUE TITLE
[☠] Сайт не открывается - [☺] Ваш провайдер не блокирует сайты.

### ISSUE THREAD

**Issue by S-ed** [ValdikSS/blockcheck#30]
> Открываем https://2chru.net/
    [☠] Сайт не открывается

> [!] Результат:
    [☺] Ваш провайдер не блокирует сайты.

blockcheck_0.0.6.2

В браузере же:

> 2chru.net uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. The certificate is only valid for zapret.at-home.ru (Error code: sec_error_unknown_issuer)

В дополнение, можно потестить
http://danbooru.donmai.us
http://www.furaffinity.net

Пара интерсных моментов, на первый скрипт не обратил внимание:

![screenshot_1447691097](https://cloud.githubusercontent.com/assets/3008353/11187595/15c45dd0-8c98-11e5-938d-f8427d93163b.png)
![screenshot_1447691169](https://cloud.githubusercontent.com/assets/3008353/11187596/15c8580e-8c98-11e5-8a58-418ad88a2f81.png)

**Comment by ValdikSS** [comment]
Приложите, пожалуйста, полный лог.

**Comment by S-ed** [comment]
Я полагаю, речь шла о логе blockcheck, а не логе загрузки страницы в браузере?

```
[O] Тестируем DNS
[O] Получаем эталонные DNS с сервера
	Эталонные адреса:		['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через системный DNS:	['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через Google DNS:	['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через DNS AntiZapret:	['107.150.11.192', '107.150.11.192', '107.150.11.192', '107.150.11.192']
[✓] DNS записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем http://gelbooru.com/
[✓] Сайт открывается
	Открываем http://gelbooru.com/index.php?page=post&s=view&id=1989610
[✓] Сайт открывается
	Открываем http://sukebei.nyaa.se/
[✓] Сайт открывается
	Открываем http://sukebei.nyaa.se/?page=view&tid=395631
[✓] Сайт открывается
	Открываем через прокси http://gelbooru.com/
[✓] Сайт открывается
	Открываем через прокси http://gelbooru.com/index.php?page=post&s=view&id=1989610
[✓] Сайт открывается
	Открываем через прокси http://sukebei.nyaa.se/
[✓] Сайт открывается
	Открываем через прокси http://sukebei.nyaa.se/?page=view&tid=395631
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем https://2chru.net/
[☠] Сайт не открывается
	Открываем https://e621.net/
[✓] Сайт открывается

[!] Результат:
[☺] Ваш провайдер не блокирует сайты.
```

p.s.: к сожалению, я давно поменял DNS на адреса Google и не мог найти адреса провайдера. надеюсь, это не сильно повлияло на чистоту эксперимента

**Comment by ValdikSS** [comment]
Какой-то странный у вас провайдер. Попробуйте в браузере ссылку открыть, сама страница открывается?
http://sukebei.nyaa.se/?page=view&tid=395631

**Comment by S-ed** [comment]
Не спорю.
![screenshot_1447768699](https://cloud.githubusercontent.com/assets/3008353/11213338/826ed348-8d4c-11e5-8455-6e101a8d90a3.png)
![screenshot_1447768850](https://cloud.githubusercontent.com/assets/3008353/11213384/cfeb4aca-8d4c-11e5-9903-a30678c18e2f.png)

**Comment by ValdikSS** [comment]
Должно заработать, проверьте.

**Comment by ValdikSS** [comment]
У вас что-то непонятное с провайдером, он не блокирует страницы, внесенные в реестр, но отдельные файлы, расположенные на странице, блокирует, хоть их и нет в реестре. У вас, может, какой-то способ обхода блокировки в браузере установлен, что он так себя ведет?

**Comment by S-ed** [comment]
Нет. Только днс поменян.
Увы у меня нет 3го питона, только 2.7 и он ругается на дефайн принта. Подожду бинарника. =Р

**Comment by ValdikSS** [comment]
Сделаю чуть позже сегодня.

**Comment by S-ed** [comment]
Не тороплюсь.
Только что заметил, sukebei.nyaa.eu блокирует полностью.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/blockcheck/releases/tag/0.0.6.3

**Comment by ValdikSS** [comment]
Все нормально работает? Проблема устранена?

**Comment by S-ed** [comment]
```
[O] Тестируем DNS
[O] Получаем эталонные DNS с сервера
	Эталонные адреса:		['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через системный DNS:	['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через Google DNS:	['104.25.118.23', '104.25.119.23', '212.47.251.61', '5.178.68.100', '69.165.95.242']
	Адреса через DNS AntiZapret:	['107.150.11.192', '107.150.11.192', '107.150.11.192', '107.150.11.192']
[✓] DNS записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем http://sukebei.nyaa.se/
[✓] Сайт открывается
	Открываем http://gelbooru.com/index.php?page=post&s=view&id=1989610
[✓] Сайт открывается
	Открываем http://gelbooru.com/
[✓] Сайт открывается
	Открываем http://sukebei.nyaa.se/?page=view&tid=395631
[✓] Сайт открывается
	Открываем через прокси http://sukebei.nyaa.se/
[✓] Сайт открывается
	Открываем через прокси http://gelbooru.com/index.php?page=post&s=view&id=1989610
[✓] Сайт открывается
	Открываем через прокси http://gelbooru.com/
[✓] Сайт открывается
	Открываем через прокси http://sukebei.nyaa.se/?page=view&tid=395631
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем https://2chru.net/
[☠] Сертификат подменяется
	Открываем https://e621.net/
[✓] Сайт открывается

[!] Результат:
[⚠] Ваш провайдер лезет в HTTPS.
```
p.s.: У Вас там два релиза названы 0.0.6.2 (не 6.3)

**Comment by ValdikSS** [comment]
>p.s.: У Вас там два релиза названы 0.0.6.2 (не 6.3)
Починено. А вывод такой и должен быть.
