### ISSUE TITLE
Cannot find "dns.resolver"

### ISSUE THREAD

**Issue by kisik21** [ValdikSS/blockcheck#31]
Я пытаюсь запустить скрипт на elementary OS Freya (Ubuntu-derivative), но скрипт выдает мне 
ImportError: No module named 'dns'
Какие пакеты поставить, чтобы dns появился?

**Comment by ValdikSS** [comment]
См. README.md:

>Установка
>
>Для работы скрипта требуется модуль dnspython3. Установить его можно из репозитория вашего дистрибутива, или используя pip: pip install -r requirements.txt

**Comment by kisik21** [comment]
Дело в том, что я пытался сделать через pip. Модуль ставился, но, видимо, ставился криво, не в ту папку, поэтому не работал. Сейчас попробую еще разочек на чистой системе, авось заработает, и отпишусь.

**Comment by ValdikSS** [comment]
Нужно запускать pip от root. Он устанавливает его в системную папку с модулями python. И нужен python 3, а не python 2.

**Comment by ValdikSS** [comment]
Возможно, в ubuntu он называется pip3. В общем, запустите:
`sudo python3 -m pip install dnspython3`

**Comment by kisik21** [comment]
Питон третьей версии стоит, пип запускаю от рута (пакетный менеджер все же, логично).
Команда <code>sudo python3 -m pip install dnspython3</code> выдала, что не знает модуля pip.
Команда <code>sudo pip3 install dnspython3</code> тоже показала фигу, ибо программы такой не нашлось даже в репозиториях.
После запуска <code>sudo python3 /usr/bin/pip install dnspython3</code> я получил ошибку pkg_resources.DistributionNotFound: pip==1.5.4
В общем, пип был для python2.7. Сейчас ставлю pip3. В Бубунте он python3-pip называется - и что это я не догадался?
