### ISSUE TITLE
Проверка подмены https сертификатов скорее всего не работает

### ISSUE THREAD

**Issue by aronovp** [ValdikSS/blockcheck#32]
Добрый день. 
При запуске утилиты (windows) выдается такой результат:
[O] Тестируем HTTPS
	Открываем https://e621.net/
[✓] Сайт открывается
	Открываем https://2chru.net/
[☠] Сертификат подменяется

[!] Результат:
[⚠] Ваш провайдер лезет в HTTPS.

При этом результат аналогичный как в случае работы через vpn так и напрямую.
В браузере сертификаты обоих доменов  выглядят  не подмененными.

**Comment by ValdikSS** [comment]
Бичи с 2chru.net не продлевают сертификат, поэтому blockcheck и считает его неверным. Что-нибудь придумаю.

**Comment by ValdikSS** [comment]
Попробуйте новую версию:
https://github.com/ValdikSS/blockcheck/releases/tag/0.0.6.4

**Comment by aronovp** [comment]
Спасибо огромное. Теперь все нормально.
