### ISSUE TITLE
Неработающие сайты воспринимаются как «полный DPI»

### ISSUE THREAD

**Issue by Acharvak** [ValdikSS/blockcheck#33]
На данный момент http://sukebei.nyaa.se/ лежит. Так как скрипт не может его открыть, в т.ч. через прокси, он воспринимает это как блокировку через «полный DPI».

Предлагаю встроить проверку через сторонний сервер, например isup.me. Если и он не может достучаться до сайта, не учитывать этот сайт вообще. Конкретно для isup.me есть скрипт вот здесь: https://github.com/fenhl/isup

Могу прислать пулл-реквест, когда будет время, если нет идеи лучше.

**Comment by ValdikSS** [comment]
Он, вроде, не лежит, а у него какая-то анти-DDoS-защита, похоже, такая. Подумаю над этим.

**Comment by ValdikSS** [comment]
Заменил его на rule34.xxx, BlockCheck работает.

**Comment by Acharvak** [comment]
Это решает проблему на данный момент, но ведь это может повториться в будущем?

**Comment by ValdikSS** [comment]
Да, поэтому я не закрываю тикет.

**Comment by Acharvak** [comment]
Понятно. Ладно, заморочусь с этим пулл-реквестом.

**Comment by ValdikSS** [comment]
Fixed
