### ISSUE TITLE
Как запустить?

### ISSUE THREAD

**Issue by valens254** [ValdikSS/blockcheck#34]
Может глупый вопрос, но как?
python ./blockcheck.py
  File "./blockcheck.py", line 88
    def print(*args, **kwargs):
            ^
SyntaxError: invalid syntax
Вот что мне выдаёт.

**Comment by ValdikSS** [comment]
`./blockcheck.py`
или
`python3 ./blockcheck.py`

**Comment by valens254** [comment]
python3 ./blockcheck.py
Traceback (most recent call last):
  File "./blockcheck.py", line 9, in <module>
    import dns.resolver
ImportError: No module named 'dns'

**Comment by ValdikSS** [comment]
Внимательно читайте readme.

**Comment by valens254** [comment]
pip install -r requirements.txt Запускал

**Comment by valens254** [comment]
pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): dnspython3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))

**Comment by ValdikSS** [comment]
pip3 попробуйте. Узнавайте, как в вашем дистрибутиве использовать pip из Python 3.

**Comment by valens254** [comment]
Спасибо.

**Comment by valens254** [comment]
python3 -m pip

**Comment by Kakadu** [comment]
В убунтах ещё есть pip3 пакет
