### ISSUE TITLE
Останавливается на  https://e621.net/

### ISSUE THREAD

**Issue by a4test** [ValdikSS/blockcheck#36]
Не показывает результат, останавливаясь на	Открываем https://e621.net/
Видимо изза 
ssl_error_bad_cert_domain 
e621.net использует недействительный сертификат безопасности. Сертификат действителен только для следующих имён: *.netbynet.ru, netbynet.ru

**Comment by ValdikSS** [comment]
Зависает полностью, после 15 секунд ничего не происходит?

**Comment by a4test** [comment]
Да, на полчаса оставлял. Гуи не зависает, прокрутка работает

**Comment by ValdikSS** [comment]
Есть ли у вас возможность предоставить мне удаленный доступ в вашу сеть или к вашему компьютеру? Напишите на iam@valdikss.org.ru (email или jabber), пожалуйста.

**Comment by ValdikSS** [comment]
Можете ли предоставить какую-то информацию?
