### ISSUE TITLE
Статистика по провайдерам и их способам блокировки

### ISSUE THREAD

**Issue by reallyuniquename** [ValdikSS/blockcheck#37]
Привет. Где-то можно посмотреть, какие способы блокировки используют конкректные провайдеры? Меня интересуют московские. Возможно, вы сами собирали такую статистику.

**Comment by ValdikSS** [comment]
Могу сделать таблицу только в следующем месяце, не раньше.

**Comment by reallyuniquename** [comment]
Отлично, буду ждать.

**Comment by reallyuniquename** [comment]
Какие-нибудь новости?

**Comment by ValdikSS** [comment]
Какие конкретно провайдеры вас интересуют?

**Comment by reallyuniquename** [comment]
Москва: Акадо, ОнЛайм, Seven Sky.

**Comment by reallyuniquename** [comment]
Что-нибудь есть?

**Comment by ValdikSS** [comment]
Вы можете предоставить интересующие вас диапазоны адресов у этих провайдеров? Имена провайдеров в старой статистике я получал из базы MaxMind за 2013, кажется, год, и сейчас она уже, думаю, безнадежно устарела, а покупать новую не очень хочется.

**Comment by reallyuniquename** [comment]
Пожалуй, сейчас я такие данные предоставить вам не могу. Зато есть базы MaxMind за август 2015.

**Comment by ValdikSS** [comment]
В общем, если вы не против, я могу дать вам .sql-выгрузку сырых данных без последнего октета в IP-адресе, и делайте с ней что угодно.

**Comment by reallyuniquename** [comment]
Меня такой вариант очень даже устраивает.

**Comment by culhatsker** [comment]
Могу ли я тоже получить такую базу?

**Comment by ValdikSS** [comment]
Кидайте свои емейлы, что ли.

**Comment by culhatsker** [comment]
egor.tyuvaev@gmail.com

**Comment by ValdikSS** [comment]
@reallyuniquename и вы тоже

**Comment by reallyuniquename** [comment]
Отписал на вашу почту из профиля.

**Comment by reallyuniquename** [comment]
Пока ничего не приходило.

**Comment by ValdikSS** [comment]
Отправил.
