### ISSUE TITLE
Рутрекер

### ISSUE THREAD

**Issue by resetnow** [ValdikSS/blockcheck#39]
У ТТК рутрекер заблокирован как-то по-особенному, все сайты просто через провайдерский DNS, а там то ли DPI, то ли еще что. В связи с шумихой вокруг рутрекера имеет смысл добавить его в список проверяемых ресурсов.

**Comment by madmaximka** [comment]
под vpn также не работает?

20 февраля 2016 г., 22:13 пользователь Vlad Ivanov <notifications@github.com

**Comment by resetnow** [comment]
Работает, конечно. Это блокировка провайдера.

**Comment by resetnow** [comment]
Добавил вот так:

```patch
diff --git a/blockcheck.py b/blockcheck.py
index de31f12..2abfa64 100755
--- a/blockcheck.py
+++ b/blockcheck.py
@@ -24,6 +24,8 @@ http_list = {'http://gelbooru.com/':
                  {'status': 200, 'lookfor': 'Rule 34', 'ip': '178.21.23.224'},
              'http://rule34.xxx/index.php?page=post&s=view&id=879177':
                  {'status': 200, 'lookfor': 'Rule 34', 'ip': '178.21.23.224'},
+             'http://rutracker.org/':
+                 {'status': 200, 'lookfor': 'BitTorrent трекер RuTracker.org', 'ip': '195.82.146.214'},
             }
 
 https_list = {'https://2chru.cafe/', 'https://e621.net/'}
```

```
[!] Результат:
[⚠] У вашего провайдера "полный" DPI. Он отслеживает ссылки даже внутри прокси, поэтому вам следует использовать любое шифрованное соединение, например, VPN или Tor.
```

**Comment by resetnow** [comment]
Результат для рутрекера:

```
[O] Тестируем обход DPI
	Пробуем способ: фрагментирование заголовка
[☠] Сайт не открывается
	Пробуем способ: перенос строки в заголовках в UNIX-стиле
[✓] Сайт открывается
	Пробуем способ: заголовок host вместо Host
[✓] Сайт открывается
	Пробуем способ: точка в конце домена
[✓] Сайт открывается
	Пробуем способ: необычный порядок заголовков
[✓] Сайт открывается
	Пробуем способ: дополнительный пробел после GET
[✓] Сайт открывается
```

**Comment by ValdikSS** [comment]
А не для рутрекера?

**Comment by resetnow** [comment]
Не для рутрекера блокировка осуществляется по провайдерскому DNS. У меня гугловские стоят, показывает, что вообще нет блокировки (ответы от чужих DNS не подменяются). Рутрекер в этом плане особенный (и пока единственный). 

Думаю теперь, как бы сделать автоматическую модификацию заголовков, чтобы вообще прозрачно. Теоретически, можно на роутере определенные IP пускать через прозрачный squid и там модифицировать.

**Comment by ValdikSS** [comment]
А https://2chru.net не такой же особенный?

**Comment by resetnow** [comment]
Нет, с ним все нормально.

**Comment by resetnow** [comment]
Хотя нет, он сначала говорит об ошибке сертификата, а потом показывает пустую страницу. Это я по HTTP открыл, он редиректит на другой домен. Сейчас посмотрю подробнее.

**Comment by ValdikSS** [comment]
Так и должно быть. Сертификат, вероятно, не подменяется, и DNS тоже.

**Comment by resetnow** [comment]
Да, он не подменяется (просто просрочен) и там не пустая страница, а ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY. Что под VPN, что без. Так что он тоже не особенный.

**Comment by ValdikSS** [comment]
Исправлено в commit 7915d6b04e6c37a9719154e268b0e4c7f7f4d0aa и commit 7425e256a2389843f6841e7e06a74b9639607409

**Comment by resetnow** [comment]
Спасибо! :+1:
