### ISSUE TITLE
Ошибка при определении блокировки https

### ISSUE THREAD

**Issue by IRainman** [ValdikSS/blockcheck#58]
Суть ошибки три ссылки открылись, а одна нет.

BlockCheck v0.0.9.2
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
IP: НЕВАЖНО, провайдер: НЕВАЖНО
[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100', '67.202.114.133', '67.202.114.134']
	Через Google DNS:	 ['104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100', '67.202.114.133', '67.202.114.134']
	Через Google API:	 ['104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100', '67.202.114.133', '67.202.114.134']
	Несуществующий DNS не вернул адресов (это не ошибка)
[✓] DNS-записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[✓] Сайт открывается
	Открываем  http://furry.booru.org/
[✓] Сайт открывается
	Открываем  http://pbooru.com/
[✓] Сайт открывается
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[✓] Сайт открывается
	Открываем  http://rutracker.org/forum/index.php
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем  https://lolibooru.moe/
[✓] Сайт открывается
	Открываем  https://e621.net/
[✓] Сайт открывается
	Открываем  https://rutracker.org/forum/index.php
[✓] Сайт открывается
	Открываем  https://dailymotion.com/
[☠] Сайт не открывается
[☠] isup.me не поддерживает HTTPS, считаем, что сайт работает, а проблемы только у нас

[!] Результат:
[⚠] Ваш провайдер полностью блокирует доступ к HTTPS-сайтам из реестра.

**Comment by ValdikSS** [comment]
В чем ошибка? На деле не так? На деле dailymotion открывается?

**Comment by IRainman** [comment]
Хм, прошу прощения, видимо какой то локальный глюк был..

BlockCheck v0.0.9.2
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
IP: 188.255.29.xxx, провайдер: National cable Networks/ OnLime

[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100', '67.202.114.133', '67.202.114.134']
	Через Google DNS:	 ['104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100', '67.202.114.133', '67.202.114.134']
	Через Google API:	 ['104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100', '67.202.114.133', '67.202.114.134']
	Несуществующий DNS не вернул адресов (это не ошибка)
[✓] DNS-записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем  http://pbooru.com/
[✓] Сайт открывается
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается
	Открываем  http://rutracker.org/forum/index.php
[✓] Сайт открывается
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[✓] Сайт открывается
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[✓] Сайт открывается
	Открываем  http://furry.booru.org/
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем  https://e621.net/
[✓] Сайт открывается
	Открываем  https://dailymotion.com/
[✓] Сайт открывается
	Открываем  https://lolibooru.moe/
[✓] Сайт открывается
	Открываем  https://rutracker.org/forum/index.php
[✓] Сайт открывается

[!] Результат:
[☺] Ваш провайдер не блокирует сайты.
