### ISSUE TITLE
Разделить проверки IPv6 и IPv4

### ISSUE THREAD

**Issue by nshopik** [ValdikSS/blockcheck#59]
Тунельный IPv6 (не teredo/6to4) вводит в смуты в результаты ответов. Допустим он определяет провайдера как полный DPI где его нет.

Я думаю имеет смысл полностью разделить проверки как независимые друг от друга по IPv4 и IPv6 сети.

**Comment by ValdikSS** [comment]
Это планируется после Великого Рефакторинга. IPv6-туннели — явление редкое. Люди, которые их настраивают, технически подкованные, понимают, что делают, и могут его отключить или воспользоваться `--disable-ipv6`.

**Comment by nshopik** [comment]
Я думаю здесь речь не в тунелях, а о том что IPv6 и IPv4 проверки в одной куче а не две независимые.

Раз рефакторинг в плане где будет это раздельно, закрываю
