### ISSUE TITLE
Украинская блокировка

### ISSUE THREAD

**Issue by GoodGuyNick** [ValdikSS/blockcheck#62]
В связи с блокировкой на Украине, добавьте ресурсы для тестирования.

**Comment by ValdikSS** [comment]
Есть ли нормальный список заблокированных ресурсов? Правильно ли я понимаю, что заблокированы все ресурсы Яндекс, Mail.ru (включая и все сторонние, которые так или иначе используют инфраструктуру: одноклассники, другие сайты), Вконтакте (использует отдельную от mail.ru инфраструктуру), Лаборатории Касперского и DrWEB. Что-то еще?

http://newsonline24.com.ua/ves-spisok-rossijskix-sajtov-kotorye-zablokirovany-v-ukraine/ — этот список полный?

**Comment by nshopik** [comment]
1c вероятно тоже там должен быть

**Comment by GoodGuyNick** [comment]
Вроде полный. Абсолютно полный и точный список появится спустя время. Киевстаром https://www.kaspersky.ua/ еще не блокируется, если будет блокироваться в будущем.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/blockcheck/wiki/Сообщение-украинцам

**Comment by ValdikSS** [comment]
Можно пробовать: https://github.com/ValdikSS/blockcheck/releases/tag/ua%2F0.0.9.4-rc1

**Comment by ValdikSS** [comment]
Исправил ошибку с DNS:
https://github.com/ValdikSS/blockcheck/releases/tag/ua%2F0.0.9.4-rc2

**Comment by alex-connor** [comment]
а будет ли билд версии под Украину для macOS?

**Comment by ValdikSS** [comment]
Он не нужен. Провайдеры Украины, в своем подавляющем большинстве, блокируют по IP-адресу. Blockcheck писался под разнообразие блокировок в России, а на Украине ничего интересного.

**Comment by alex-connor** [comment]
Не знаю как кто блокирует, воля, например, использует подмену ДНС, насколько я понимаю... Смена ДНС на альтернативные не помогла. Слышал про этот тест, думал проверить, но не нашел версии под mac... Придется разворачивать виртуалку с виндой
