### ISSUE TITLE
Просьба вернуть архив с кучей файлов как альтернативный вариант для загрузки или сделать инсталлятор.

### ISSUE THREAD

**Issue by IRainman** [ValdikSS/blockcheck#64]
Поясню зачем нужно. У меня везде настроено SRP и запускать исполняемые файлы из TEMP просто нельзя. Соответственно архив мне очень удобен ибо уже давно написан простой инсталляционный скрипт, который кладёт содержимое архива в ProgramFiles а оттуда SRP уже разрешает запуск :)

Вынуть из экзешки содержимое я ничем не смог поэтому прошу вернуть архив или сделать msi файл для установки который сам бы клал файлы в ProgramFiles и ярлычок клал в "меню пуск" :)

P.S. на текущий момент был вынужден откатиться на 0.0.9.1

P.P.S. ![](https://habrastorage.org/web/32b/5d9/bbe/32b5d9bbe2e348ef8cae1a613ff9005a.PNG)

**Comment by ValdikSS** [comment]
Вам так часто нужно запускать blockcheck? Установить python и запускать версию из репозитория неудобно?Внутри exe должен быть какой-то распространенный формат архивирования, вечером напишу, как его распаковать.

**Comment by IRainman** [comment]
Частенько необходимо с нетбука для диагностики сетей, потому обновляюсь часто.

Python ставить из репы не хочу ибо и до этого всё хорошо работало :) к тому же этот язык очень сильно зависит от версий, пусть уж лучше будет портативно лежать с утилитой.

Благодарю, подожду вечера. Собственно я из-за лени ишью написал: нажал Ctrl+PgDown в TotalCommander а оно не открылось, ну а дальше мне уже копаться было лень.

**Comment by ValdikSS** [comment]
Хм, там файлы по отдельности зажаты zlib'ом, просто так распаковать не выйдет.
Можете воспользоваться [PyInstaller Extractor](https://sourceforge.net/projects/pyinstallerextractor/) или просто скопировать файлы из временной папки, не закрывая окно с ошибкой из первого сообщения.

**Comment by ValdikSS** [comment]
Проблема решена?

**Comment by IRainman** [comment]
Миу, благодарю что спросил. Теперь буду квест делать: запускать в тотале под админом, копировать вручную из временной папки куда надо и закрывать. Грустненько.

Для настоящего решения проблемы (без костылей) крайне желательно, например, сделать с запуском из командной строки с параметром или просто MSI файл, который раскладывает файлы сразу в Program Files.

**Comment by IRainman** [comment]
Ну как, что нибудь планируется с этим делать или теперь всё? :( Вынужденно продолжаю сидеть на версии из архива blockcheck_0.0.9.1.rar ибо вытащить нужное из текущих дистрибов не представляю как, а возиться с установкой и обновлением питона на винде это целый геморой.

**Comment by ValdikSS** [comment]
https://files.catbox.moe/qs180w.zip

**Comment by IRainman** [comment]
Благодарю, архив помог :) Если можно, то, пожалуйста, к будущим релизам делай такой же архив.

**Comment by ValdikSS** [comment]
Хорошо.

**Comment by IRainman** [comment]
Миу, будущее наступило, архива нет :) Хотел проверить что изменилось в новой версии, но не могу. Старая exe для python 3.6, а в папке в temp уже 3.7 и опять ничего не работает. Может всё же выложишь архив в релизы? Тяжко очень ибо.

**Comment by ValdikSS** [comment]
Готово. Теперь релиз в папке будет выкладываться вместе с exe-файлами.
