### ISSUE TITLE
неверное определение

### ISSUE THREAD

**Issue by TheChief5055** [ValdikSS/blockcheck#67]
Провайдер Связьинформ. BlockCheck утверждает, что подменяются только DNS-записи, но это не так. При попытке открыть ресурс провайдер отдаёт вот это:

[closed.zip](https://github.com/ValdikSS/blockcheck/files/1220720/closed.zip)

БЧ считает при этом, что сумел открыть тестируемый сайт.

**Comment by ValdikSS** [comment]
Приложите полный вывод blockcheck.

**Comment by TheChief5055** [comment]
BlockCheck v0.0.9.5
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
IP: 213.234.31.xxx, провайдер: JSC UNICO/ UNICO

[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['5.178.68.100', '92.255.241.100', '92.255.241.100', '92.255.241.100', '92.255.241.100', '92.255.241.100']
	Через Google DNS:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100']
	Через Google API:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.146.95', '195.8.215.136', '195.82.146.214', '5.178.68.100']
	Несуществующий DNS не вернул адресов (это не ошибка)
[☠] DNS-записи подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP (по настоящим IP-адресам сайтов)
	Открываем  http://furry.booru.org/
[✓] Сайт открывается
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[✓] Сайт открывается
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[✓] Сайт открывается
	Открываем  http://rutracker.org/forum/index.php
[✓] Сайт открывается
	Открываем  http://pbooru.com/
[✓] Сайт открывается
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем  https://www.dailymotion.com/
[✓] Сайт открывается
	Открываем  https://rutracker.org/forum/index.php
[✓] Сайт открывается
	Открываем  https://lolibooru.moe/
[✓] Сайт открывается
	Открываем  https://e621.net/
[✓] Сайт открывается

[O] Тестируем обход DPI
	Пробуем способ «заголовок hoSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «необычный порядок заголовков» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «табуляция в конце домена» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «дополнительный пробел после GET» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «точка в конце домена» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки перед GET» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «заголовок hoSt вместо Host» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «необычный порядок заголовков» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «табуляция в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «дополнительный пробел после GET» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «точка в конце домена» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «перенос строки перед GET» на pbooru.com
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на pbooru.com
[✓] Сайт открывается

[!] Результат:
[⚠] Ваш провайдер подменяет DNS-записи, но не перенаправляет сторонние IPv4 DNS-серверы на свой.
 Вам поможет смена DNS, например, на Яндекс.DNS 77.88.8.8 или Google DNS 8.8.8.8 и 8.8.4.4.
[☺] Ваш провайдер не блокирует сайты.

**Comment by TheChief5055** [comment]
Я предполагаю, что это результаты работы ПО www.zapretservice.ru, т.е. прозрачный прокси на squid.

**Comment by ValdikSS** [comment]
Это не соответствует действительности?
Покажите вывод:
`curl -H "Host: rutracker.org" -v -o /dev/null http://195.82.146.214/forum/index.php`
и
`curl -H "Host: rutracker.org" -0 -v -o /dev/null http://195.82.146.214/forum/index.php`

**Comment by ValdikSS** [comment]
Вы сможете выполнить эти команды?

**Comment by ValdikSS** [comment]
Нет ответа.
