### ISSUE TITLE
Запуск и логирование

### ISSUE THREAD

**Issue by kifat** [ValdikSS/blockcheck#68]
Система - Win7
.exe версия - все работает прекрасно, провайдер блочит (с goodbyeDPI - не блочит :D, спасибо за программку). Но - я не могу скопировать результаты, текст в логе выделить можно, скопировать - нет (правая кнопка, Ctrl+C - не происходит ничего)

питоновская версия - не запускается. Какой питон нужен? (Так уж вышло, что я использовал некоторые программы на питоне - и они вполне корректно открывались двойным щелчком после прописывания файловых ассоциаций. Сейчас стоит версия 3.5.3)

**Comment by ValdikSS** [comment]
Нужен любой python 3. Версия 3.4 и выше. Нужно установить модули из requirements.txt. В readme указано, как это сделать.

**Comment by ValdikSS** [comment]
Ctrl+C должен работать, но только на английской раскладке. Попробуйте переключить раскладку.

**Comment by kifat** [comment]
Да, с английской раскладкой работает. Забыл проверить этот вариант, хотя и сталкивался с чем-то подобным (но редко). Спасибо
