### ISSUE TITLE
Windows XP & blockcheck

### ISSUE THREAD

**Issue by Baltazar500** [ValdikSS/blockcheck#70]
Под XP тулза не работает :

---------------------------
blockcheck-0.0.9.5-windows.exe - Точка входа не найдена
---------------------------
Точка входа в процедуру GetFinalPathNameByHandleW не найдена в библиотеке DLL KERNEL32.dll. 

###

---------------------------
Fatal Error!
---------------------------
Error loading Python DLL: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\_MEI25842\python35.dll (error code 127)

**Comment by ValdikSS** [comment]
Не работает, и работать не будет. Windows XP давно не поддерживается. Используйте современную ОС.
