### ISSUE TITLE
blockcheck-0.0.9.5 - Fatal Error

### ISSUE THREAD

**Issue by MegaCron** [ValdikSS/blockcheck#72]
Windows 7 x64, при запуске blockcheck-0.0.9.5-windows.exe --console --no-report --disable-ipv6 программа  выплёвывает 2 ошибки и закрывается :

---------------------------
blockcheck-0.0.9.5-windows.exe - Точка входа не найдена
---------------------------
Точка входа в процедуру ucrtbase.terminate не найдена в библиотеке DLL api-ms-win-crt-runtime-l1-1-0.dll. 

---------------------------
Fatal Error!
---------------------------
Error loading Python DLL: C:\Users\Admin\AppData\Local\Temp\_MEI54122\python35.dll (error code 127)

Заметил, что появился билд 0.0.9.6, но пока нет возможности его проверить (только позже).

**Comment by ValdikSS** [comment]
Вероятно, нужно установить Microsoft VC Runtime 2015
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by MegaCron** [comment]
Заработало.  Вопрос решён.
