### ISSUE TITLE
Не работает определение провайдера и IP-адреса

### ISSUE THREAD

**Issue by ValdikSS** [ValdikSS/blockcheck#73]
Сайт 2ip.ru, используемый для определения провайдера, перешел на HTTPS и требует корректного User-Agent.

**Comment by FTOH** [comment]
Как насчет http://ip-api.com/ ?

**Comment by ValdikSS** [comment]
Я починил 2ip, но еще не закоммитил.

**Comment by ValdikSS** [comment]
Исправлено в версии 0.0.9.7.
