### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by hadisfr** [ValdikSS/blockcheck#78]
What do you think about add other languages, specially English, to the program?
Even though it has been designed for Russia initially, I think it may be rather useful in some other countries, specially those who may by some censorship tools from the Russian Government. I'm using google translate to understand output now.

**Comment by NNM42** [comment]
this app specific for ru segment.

**Comment by ValdikSS** [comment]
@hadisfr, this application is bound to Russian block list. Take a look at [OONI](https://ooni.torproject.org/), it is a quite similar worldwide project.
