### ISSUE TITLE
Version 0.0.9.6 use incorrect url for http test because it's redirected to https and not working

### ISSUE THREAD

**Issue by IRainman** [ValdikSS/blockcheck#79]
Hello!

The problem log:
	Открываем  http://furry.booru.org/
[☠] Сайт не открывается, пробуем через прокси
[✓] Сайт открывается через прокси
	Открываем  http://furry.booru.org/index.php?......
[☠] Сайт не открывается, пробуем через прокси
[✓] Сайт открывается через прокси

This is an error because proxy following redirects automatically and open this links correctly. This URLs working fine without proxy but redirected to https version of the site.

P.S. sorry for english, I don't have russian keyboard on this device ^_^'

**Comment by ValdikSS** [comment]
Странно, у меня работает:
```
        Открываем  http://furry.booru.org/
[✓] Сайт открывается
        Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[✓] Сайт открывается
…
```
Можете сделать дамп трафика?

**Comment by NNM42** [comment]
Все работает. Тоже проверил.

**Comment by IRainman** [comment]
> Можете сделать дамп трафика?
Могу, а чем и как лучше это сделать? 
P.S. у меня есть подозрение что это из-за шлюза (Kerio Control) может быть но я не уверен.

**Comment by ValdikSS** [comment]
@IRainman лучше всего использовать [Wireshark](https://www.wireshark.org/)
Инструкция: https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
@IRainman, проблема ещё наблюдается? Сможете предоставить дамп трафика?

**Comment by IRainman** [comment]
Проблема всё ещё наблюдается.
Если проверять с выключенными маршрутами в цивилизацию то вот так:
==========================================================
BlockCheck v0.0.9.8
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
IP: 178.140.0.xxx, провайдер: Rostelecom/ Ростелеком МРФ "Центр"

[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['104.18.182.1', '104.18.183.1', '104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '195.8.215.136', '195.82.146.214', '208.100.28.56', '67.202.114.141']
	Через Google DNS:	 ['104.18.182.1', '104.18.183.1', '104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '195.8.215.136', '195.82.146.214', '208.100.28.56', '67.202.114.141']
	Через Google API:	 ['104.18.182.1', '104.18.183.1', '104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '195.8.215.136', '195.82.146.214', '208.100.28.56', '67.202.114.141']
	Несуществующий DNS не вернул адресов (это не ошибка)
[✓] DNS-записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается
	Открываем  http://furry.booru.org/
[✓] Сайт открывается
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[☠] Получен неожиданный ответ, скорее всего, страница-заглушка провайдера. Пробуем через прокси.
[✓] Сайт открывается через прокси
	Открываем  http://pbooru.com/
[✓] Сайт открывается
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[☠] Получен неожиданный ответ, скорее всего, страница-заглушка провайдера. Пробуем через прокси.
[✓] Сайт открывается через прокси
	Открываем  http://rutracker.org/forum/index.php
[☠] Получен неожиданный ответ, скорее всего, страница-заглушка провайдера. Пробуем через прокси.
[✓] Сайт открывается через прокси

[O] Тестируем HTTPS
	Открываем  https://e621.net/
[☠] Сайт не открывается
	Открываем  https://lolibooru.moe/
[☠] Сайт не открывается
	Открываем  https://rutracker.org/forum/index.php
[☠] Сайт не открывается
	Открываем  https://www.dailymotion.com/
[☠] Сайт не открывается

[O] Тестируем обход DPI
	Пробуем способ «дополнительный пробел после GET» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «заголовок hOSt вместо Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «заголовок hoSt вместо Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «значение Host БОЛЬШИМИ БУКВАМИ» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «необычный порядок заголовков» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «перенос строки перед GET» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «табуляция в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «дополнительный пробел после GET» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «заголовок hOSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «заголовок hoSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «значение Host БОЛЬШИМИ БУКВАМИ» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «необычный порядок заголовков» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки перед GET» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «табуляция в конце домена» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на rutracker.org
[✓] Сайт открывается

[!] Результат:
[⚠] Ваш провайдер полностью блокирует доступ к HTTPS-сайтам из реестра.
[⚠] У вашего провайдера "обычный" DPI. Вам поможет HTTPS/Socks прокси, VPN или Tor.
==========================================================
Если на шлюзе включён обход блокировок с помощью маршрутизации и в браузере при этом всё работает корректно, то вывод утилиты абсолютно некорректный, потому что фактически блокировок нет ни по DNS, ни каким-либо другим способом и должен быть вывод  "Ваш провайдер не блокирует сайты":
==========================================================
BlockCheck v0.0.9.8
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
IP: 178.140.0.xxx, провайдер: Rostelecom/ Ростелеком МРФ "Центр"

[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['104.18.182.1', '104.18.183.1', '104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '195.8.215.136', '195.82.146.214', '208.100.28.56', '67.202.114.141']
	Через Google DNS:	 ['104.18.182.1', '104.18.183.1', '104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '195.8.215.136', '195.82.146.214', '208.100.28.56', '67.202.114.141']
	Не удалось подключиться к Google API
	Несуществующий DNS не вернул адресов (это не ошибка)
[?] Не удалось связаться с Google API. Проверка DNS сломана.

[O] Тестируем HTTP (по настоящим IP-адресам сайтов)
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается
	Открываем  http://furry.booru.org/
[☠] Сайт не открывается, пробуем через прокси
[✓] Сайт открывается через прокси
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[☠] Сайт не открывается, пробуем через прокси
[✓] Сайт открывается через прокси
	Открываем  http://pbooru.com/
[✓] Сайт открывается
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[✓] Сайт открывается
	Открываем  http://rutracker.org/forum/index.php
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем  https://e621.net/
[✓] Сайт открывается
	Открываем  https://lolibooru.moe/
[✓] Сайт открывается
	Открываем  https://rutracker.org/forum/index.php
[✓] Сайт открывается
	Открываем  https://www.dailymotion.com/
[✓] Сайт открывается

[O] Тестируем обход DPI
	Пробуем способ «дополнительный пробел после GET» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «заголовок hOSt вместо Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «заголовок hoSt вместо Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «значение Host БОЛЬШИМИ БУКВАМИ» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «необычный порядок заголовков» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «перенос строки перед GET» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «табуляция в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «дополнительный пробел после GET» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «заголовок hOSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «заголовок hoSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «значение Host БОЛЬШИМИ БУКВАМИ» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «необычный порядок заголовков» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки перед GET» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «табуляция в конце домена» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на rutracker.org
[✓] Сайт открывается

[!] Результат:
[⚠] Не удалось определить способ блокировки IPv4 DNS.
 Верните настройки DNS провайдера, если вы используете сторонний DNS-сервер. Если вы используете DNS провайдера, возможно, ответы DNS модифицирует вышестоящий провайдер.
 Вам следует использовать шифрованный канал до DNS-серверов, например, через VPN, Tor, HTTPS/Socks прокси или DNSCrypt.
[⚠] У вашего провайдера "обычный" DPI. Вам поможет HTTPS/Socks прокси, VPN или Tor.
==========================================================
Сдампить траффик попробую когда да работы доберусь, если повезёт то в этот пн, если не повезёт то через неделю.

**Comment by IRainman** [comment]
P.S. пока у меня предложение поднять свой DoH и получать гарантированно валидные IP именно с него. Поднять, например, на адресе прокси prostovpn и возвращать с него только адреса которые есть в утилите для тестирования.

**Comment by ValdikSS** [comment]
У вас намеренно сломан Google API, программа не работает корректно в этом случае.
