### ISSUE TITLE
e621.net якобы не открывается

### ISSUE THREAD

**Issue by Aloki** [ValdikSS/blockcheck#82]
Открываем  https://e621.net/
[☠] Сайт не открывается

А он открывается (в браузере), только с кодом 403 и заглушкой Cloudflare с капчей.

**Comment by ValdikSS** [comment]
Все еще наблюдается? У меня всё в порядке. Может, временно включали режим с капчей.

**Comment by Aloki** [comment]
Всё ещё наблюдается. Капча Cloudflare присутствует. Точно не временно, первый раз баг обнаружил несколько месяцев назад, но поленился создать репорт.

**Comment by ValdikSS** [comment]
Постараюсь найти сайт не за cloudflare для включения в тест.

**Comment by ValdikSS** [comment]
Воспроизвел проблему.

**Comment by ValdikSS** [comment]
Исправлено в 9dadf43d03feacd3542bb80d0a459be4aa99af2b, войдет в версию 0.0.9.8.
