### ISSUE TITLE
no $DISPLAY environment variable

### ISSUE THREAD

**Issue by Alien-hide** [ValdikSS/blockcheck#85]
Падает на centos 7
Traceback (most recent call last):
  File "blockcheck.py", line 1107, in <module>
  File "tkinter/__init__.py", line 2023, in __init__
_tkinter.TclError: no display name and no $DISPLAY environment variable

С предыдущим BlockCheck v0.0.9.6 такой проблемы нет.

**Comment by ValdikSS** [comment]
Программа пытается запуститься в графическом режиме, но не может из-за того, что у вас, видимо, не запущен X-сервер.
Это не ошибка как таковая, и странно, что раньше было иначе. Запускайте с параметром `--console`.
Сделаю проверку в следующей версии.

**Comment by ValdikSS** [comment]
Исправлено в commit 7a09a55b6f49c7ef7a7262dc27457bb856a54057, войдёт в версию 0.0.9.9.
